SECRET_KEY: ENC[AES256_GCM,data:9Sc8tTd6TayAMfzlAUXerDaOQJTAtNwjMVWCs3ppXfwSzciNYLhzsYM8cA==,iv:lpkoKwFDN6rm/g4lGn2w+DiBcSRxdpnVm/P1TWz8RHI=,tag:srgKGyI7XAWKNYeyjhC48g==,type:str]
CLIENT_ID: ENC[AES256_GCM,data:GVABq5lXszpZGzid7xgUCr2dI0AY0XiUU63fuqD86V+jwl/0sA7r,iv:MI2JaQuVmLn2OsmDimU0M86oq7OpI7kTF/AsMlP9G+M=,tag:F+ZuzEPD2m4WMGhm5LHOkA==,type:str]
CLIENT_SECRET: ENC[AES256_GCM,data:xMPCjpXw0RNASCpR5hhfcWgR90xQhrcFuWZr2MPHe7/nO+HZnXxvu52+/w==,iv:SV3jT1yG+AFsBL+O054glIXz+yNiNjSd2sHLAQKaQ8A=,tag:WbODpcFc9LFtPv+TCIsI7A==,type:str]
SENTRY_DSN: ENC[AES256_GCM,data:RJTrLGwUfBeNg/oddTvMwtxAigsEHKipe22Eiq3KcARZCt1F53yEUaUESGOhLmvV/mygh3oNaeAQcnj8n2er+TtP2dSPlsvpTlgR95XO3InUM+XqYo0p1/9ZfKUi8Zc=,iv:AeRRTS7zuzkCTOA9LoV+Z2lkDgi3LF0PN/obUnX5f1c=,tag:sQN1LVoL561ST1gNXkkyag==,type:str]
sops:
    age:
        - recipient: age186vefrtv5wncsdczd4fmrrz9x2slgcxz9ape96vsc02sqdln6f6qxfjqqy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZEQ0Ymw5OVpTVlNjZW1j
            K1ozbHBxZlJzZ3BaMTJyT25qU3loUXdNTVI4CnpoZG1xSW9LMjZ6M2llbkhuVmU5
            OUMwWTgxaWxwa0ZZdnc5QWJEUXBkTGsKLS0tIEFUbmxLSDN6THQxVThWWktkOVFE
            RitPR0J4UWVGSkxlMVlSbVljQkttYzQK7E2lsLAK7cqDPidTlx5H08ZPf+t5O2Id
            4Cih3BiZc+90YaagcPeoCRv0/r+I3vVNptp8foSzCn14w1vb4jdSng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T13:30:09Z"
    mac: ENC[AES256_GCM,data:GbeTmmFMwtZPJtKus6kY20VvdvXI7xQQdDXG3Y1U826iliBtRsw2BJu9BM3arUtBSw5fwfer87ycs3hktJawdVSMW3iKb2cJ1JZjgpGNz+dqgFDd4w/IluoeppsrKqU2AxQrbAFgKCeeHT0t/AYQN7rs1zPaau3MyGRzS7O7bAM=,iv:4uFkon6bfVdj4KcwsI5WrlZN8HskJ9LB1uD7tWUZhdM=,tag:FbFAUMKF6NrWq0KpRu3E0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
