[vars]
credentials_file = "config/credentials/development.enc.yaml"
secret_file = "config/credentials/development.key"
uv_sync_args = "--group dev"

[settings]
sops.age_key_file = "{{vars.secret_file}}"

[env]
SOPS_AGE_KEY_FILE = "{{vars.secret_file}}"
_.file = "{{vars.credentials_file}}"

FLASK_ENV = "development"
SENTRY_ENVIRONMENT = "development"
MAVIS_BACKEND_URL = "http://localhost:4000"
MAVIS_ROOT_URL = "http://localhost:4001/"
ROOT_URL = "http://localhost:{{vars.port}}/"
