[vars]
credentials_file = "config/credentials/staging.enc.yaml"
secret_file = "config/credentials/staging.key"
uv_sync_args = "--frozen --no-dev"

[settings]
sops.age_key_file = "{{vars.secret_file}}"

[env]
SOPS_AGE_KEY_FILE = "{{vars.secret_file}}"
_.file = "{{vars.credentials_file}}"

FLASK_ENV = "staging"
# SENTRY_ENVIRONMENT = "configured by terraform/app/variables.tf in the mavis repo"
MAVIS_ROOT_URL = "http://web:4000/"
# ROOT_URL = "configured by terraform/app/variables.tf in the mavis repo"
