name: Continuous deployment
run-name: Continuous deployment of ${{ github.ref_name }} to QA and Test

on:
  push:
    branches: [next]

jobs:
  ci:
    permissions: {}
    uses: ./.github/workflows/ci.yml
    secrets: inherit
  deploy:
    needs: ci
    strategy:
      fail-fast: false
      matrix:
        environment: [qa, test]
    permissions:
      id-token: write
    uses: ./.github/workflows/deploy-application.yml
    with:
      environment: ${{ matrix.environment }}
      git_sha_to_deploy: ${{ github.sha }}
